### ISSUE TITLE
Question: why the file suffix that has the same name has been changed?

### ISSUE THREAD

**Issue by peaceshi** [Razmoth/HoYoStudio#37]
I use regex to delete same files with same sha256. Now it not working for all.
I need to change all regex.
``` C#
        var pattern = @"\bUI_MapBack_(?<X>-?\d+)_(?<Y>-?\d+)_([0-9A-F]{2,})\.png\b";
```
![image](https://user-images.githubusercontent.com/10380828/188720479-fa04556a-da2c-4dd2-bd76-a0bd6d4eab01.png)

**Comment by peaceshi** [comment]
https://github.com/kongying-tavern/it-is-a-exporter/blob/a93fc931c58368bf6f47b37ce560882529c96868/scripts/Resources.csx#L84

**Comment by Modder4869** [comment]
u can join the discord server in readme https://discord.gg/JAeB5jGdcn

**Comment by Razmoth** [comment]
Greetings @peaceshi,

To summaries, it has been reported previously that the current export behavior of `TryExportFile` was skipping files due to `UniqueID` not being so unique and therefore losing assets in the process.

The current workaround was to change the `UniqueID` to something more consistent to avoid that issue.

I had no idea that it'd affect your work/project, and I apologize for the inconvenience, If by any chance you had a discord account we can discuss further details in the discord server
